version: "3.4"
services:
 wolf-builder:
    image: wolf-base:${UBUNTU}
    user: "root:root"
    volumes:
      - $HOME/.ssh:/root/.ssh
      - /tmp/debs:/tmp/debs
    command: bash -c "source /opt/ros/${ROS_DISTRO}/setup.bash &&
                      rm -rf ros_ws/src &&
                      mkdir -p ros_ws/src &&
                      catkin_init_workspace ros_ws/src &&
                      git clone -b ${BRANCH} --recursive git@github.com:graiola/wolf.git ros_ws/src/wolf &&
                      cd ros_ws &&
                      /bin/bash ./src/wolf/setup/support/get_debians.sh &&
                      sudo dpkg -i --force-overwrite src/wolf/setup/debs/${BRANCH}/${UBUNTU}/rbdl-x86_64-linux-gnu-2.5.0.deb &&
                      /bin/bash ./src/wolf/setup/debs/${UBUNTU}/advr/install.sh &&
                      source /opt/xbot/setup.sh &&
                      catkin build -DCMAKE_BUILD_TYPE=Release &&
                      source devel/setup.bash &&
                      sudo echo 'yaml https://raw.githubusercontent.com/graiola/wolf-setup/master/config/wolf.yaml' >> /etc/ros/rosdep/sources.list.d/20-default.list &&
                      /bin/bash ./src/wolf/setup/support/debianize.sh -b ${BRANCH} &&
                      mkdir -p /tmp/debs/${BRANCH} &&
                      mv ./src/wolf/setup/debs/${BRANCH}/${UBUNTU} /tmp/debs/${BRANCH}
                     "
