x-common: &common
  user: "root:root"
  volumes:
    - $HOME/.ssh:/root/.ssh
    - /tmp/debs:/tmp/debs
  environment:
    - ROS_VERSION=${ROS_VERSION}
    - BRANCH=${BRANCH}
    - UBUNTU=${UBUNTU}
  command: ["/debs-builder-entrypoint.sh"]

services:
  wolf-builder-jammy:
    <<: *common
    image: wolf-base:jammy

  wolf-builder-noble:
    <<: *common
    image: wolf-base:noble

  wolf-builder-jammy-local:
    <<: *common
    image: wolf-base:jammy
    volumes:
      - $HOME/.ssh:/root/.ssh
      - /tmp/debs:/tmp/debs
      - $HOME/${ROS_WS}/src/wolf:/root/${ROS_WS}/src/wolf
    environment:
      - ROS_VERSION=${ROS_VERSION}
      - BRANCH=${BRANCH}
      - UBUNTU=${UBUNTU}
      - ROS_LOCAL=true
